### ISSUE TITLE
No root after update from 20170110 version

### ISSUE THREAD

**Issue by saulimabr** [boulzordev/android_device_lenovo_A6020a40#15]
I update the lineage on my phone from 20170109  to 20170122, downloaded from http://moto.shreps.fr/?dir=Lenovo%20Vibe%20K5%20%28A6020%29/ROM/Lineage.
I don't make a fresh install and after this, system works ok, but root access was disabled. In developer options> root access just have "Only ADB" option to activate root and this don't work with apps.

**Comment by Shr3ps** [comment]
Hi, that's not an issue, it's a Lineage decision, please read http://lineageos.org/Update-and-Build-Prep/

**Comment by saulimabr** [comment]
Thanks! How can I root the lastest version?
