### ISSUE TITLE
Virtual Reality options are not shown in youtube app

### ISSUE THREAD

**Issue by saulimabr** [boulzordev/android_device_lenovo_A6020a40#21]
The youtube APP don't show options for Virtual Reality like in stock rom. This option are used to watch a video in VR Glasses. 
App for Google Cardboard shows "not compatible" message in playstore, too.

**Comment by danielstuart14** [comment]
Alread fixed by this commit: https://github.com/boulzordev/android_device_lenovo_A6020/commit/1038130dab077b02252ce14e717c017b58d48bf4

@skritchz
